# Generated by Django 6.0.3 on 2026-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_images/Add image.jpg', null=True, upload_to='item_images/'),
        ),
    ]
