# Generated by Django 6.0.3 on 2026-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
